---
title: "test_report"
author: "Leah Kemp"
date: "20/08/2021"
output:
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

```{r}
# Load libraries
library(dplyr)
library(DT)
```

```{r}
# Read data and set header names (thing's I don't know what they are, set to var_*)
data <- read.table("/home/lkemp/covid_reporting_template/report_table.tsv",
                   sep = "\t",
                   col.names = c("var_1", "episerve_number", "dhb", "lineage", "date_received", "var_2", "var_3"),
                   na.strings = "NA")

# Create a column conditionally adding var_3 to lineage for table (whe partial, repeat or fail)
data <- data %>%
  mutate(lineage_extra = case_when(
  var_3 == "PARTIAL" ~ paste(lineage, "(partial)"),
  var_3 == "REPEAT" ~ paste(lineage, "(repeat)"),
  var_3 == "FAIL" ~ paste(lineage, "(fail)"),
  TRUE ~ lineage
))
```

## First table

```{r}
data %>%
  select("episerve_number", "dhb", "lineage_extra", "date_received") %>%
  knitr::kable(col.names = c("Episerve number",
                             "DHB",
                             "Lineage",
                             "Date received"))
```

```{r, eval = FALSE}
data %>%
  select("episerve_number", "dhb", "lineage_extra", "date_received") %>%
  # Put in a datatable
  datatable(selection = "single",
             filter = "top",
             rownames = FALSE,
             colnames = c("Episerve number",
                          "DHB",
                          "Lineage",
                          "Date received"),
             extensions = list("ColReorder" = NULL,
                               "Buttons" = NULL,
                               "FixedColumns" = list(leftColumns=1)),
             options = list(
               dom = "BRrltpi",
               autoWidth = TRUE,
               columnDefs = list(list(width = "200px", targets = 0)),
               lengthMenu = list(c(10, 50, -1), c("10", "50", "All")),
               ColReorder = TRUE,
               buttons =
                 list("copy",
                      list(extend = "collection",
                           buttons = c("csv", "excel", "pdf"),
                           text = "Download"),
                      I("colvis"))))
```